version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:1606@postgres:5432/kindergarten_kitchen
      - SECRET_KEY=ntaV<+8xVb0NdV~3+:;sMZB%8]:i:bwi>>Dzq]l0O\<OM_%A#+
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: .
    depends_on:
      - app
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:1606@postgres:5432/kindergarten_kitchen
      - SECRET_KEY=ntaV<+8xVb0NdV~3+:;sMZB%8]:i:bwi>>Dzq]l0O\<OM_%A#+
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
    command: celery -A app.tasks.worker.celery_app worker --loglevel=info

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1606
      - POSTGRES_DB=kindergarten_kitchen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: